# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messaging.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessaging.proto\x12\tmessaging\"\x18\n\x08\x46ilepath\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1a\n\x06\x42\x42oxes\x12\x10\n\x08jsondata\x18\x01 \x01(\t2P\n\x10MessagingService\x12<\n\x10GetBoundingBoxes\x12\x13.messaging.Filepath\x1a\x11.messaging.BBoxes\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILEPATH._serialized_start=30
  _FILEPATH._serialized_end=54
  _BBOXES._serialized_start=56
  _BBOXES._serialized_end=82
  _MESSAGINGSERVICE._serialized_start=84
  _MESSAGINGSERVICE._serialized_end=164
# @@protoc_insertion_point(module_scope)
