# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messaging.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessaging.proto\x12\tmessaging\"\x1b\n\x0b\x44\x61taRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1e\n\x0c\x44\x61taResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\'\n\x14ProcessedDataRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"/\n\x15ProcessedDataResponse\x12\x16\n\x0eprocessed_data\x18\x01 \x03(\t2\xae\x01\n\x10MessagingService\x12=\n\x08SendData\x12\x16.messaging.DataRequest\x1a\x17.messaging.DataResponse\"\x00\x12[\n\x14RequestProcessedData\x12\x1f.messaging.ProcessedDataRequest\x1a .messaging.ProcessedDataResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATAREQUEST._serialized_start=30
  _DATAREQUEST._serialized_end=57
  _DATARESPONSE._serialized_start=59
  _DATARESPONSE._serialized_end=89
  _PROCESSEDDATAREQUEST._serialized_start=91
  _PROCESSEDDATAREQUEST._serialized_end=130
  _PROCESSEDDATARESPONSE._serialized_start=132
  _PROCESSEDDATARESPONSE._serialized_end=179
  _MESSAGINGSERVICE._serialized_start=182
  _MESSAGINGSERVICE._serialized_end=356
# @@protoc_insertion_point(module_scope)
