# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messaging_pb2 as messaging__pb2


class MessagingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendData = channel.unary_unary(
                '/messaging.MessagingService/SendData',
                request_serializer=messaging__pb2.DataRequest.SerializeToString,
                response_deserializer=messaging__pb2.DataResponse.FromString,
                )
        self.RequestProcessedData = channel.unary_unary(
                '/messaging.MessagingService/RequestProcessedData',
                request_serializer=messaging__pb2.ProcessedDataRequest.SerializeToString,
                response_deserializer=messaging__pb2.ProcessedDataResponse.FromString,
                )


class MessagingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestProcessedData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessagingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendData,
                    request_deserializer=messaging__pb2.DataRequest.FromString,
                    response_serializer=messaging__pb2.DataResponse.SerializeToString,
            ),
            'RequestProcessedData': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestProcessedData,
                    request_deserializer=messaging__pb2.ProcessedDataRequest.FromString,
                    response_serializer=messaging__pb2.ProcessedDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messaging.MessagingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessagingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/messaging.MessagingService/SendData',
            messaging__pb2.DataRequest.SerializeToString,
            messaging__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestProcessedData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/messaging.MessagingService/RequestProcessedData',
            messaging__pb2.ProcessedDataRequest.SerializeToString,
            messaging__pb2.ProcessedDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
